### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by SvenJuergens** [sypets/migrate2composer#13]
hi,

many thanks for this extension :)
I just followed the instructions in the readme, but stumbled at the first instruction.

`git clone https://github.com/sypets/migrate2composere.git`
should be
`git clone https://github.com/sypets/migrate2composer.git`

**Comment by sypets** [comment]
Thanks. Is fixed.

You don't really need to clone. You can install via TER. If you install via TER, you get the latest release, if you install via clone you might get a yet unreleased development version.
