### ISSUE TITLE
Risky removal of TYPO3 Console scripts

### ISSUE THREAD

**Issue by gilbertsoft** [sypets/migrate2composer#4]
If the TYPO3 Console is not found the scripts part gets removed. This is a risky change as Composer installs do not work correctly without this scripts and the TYPO3 Console. See also the recommendations made by the Core team with the [TYPO3.CMS.BaseDistribution](https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/blob/9.x/composer.json).

https://github.com/sypets/migrate2composer/blob/21fa26771f2a32790470fd33311ee32fdfd4ccc7/Classes/Composer/Typo3ComposerManifest.php#L75-L89

The default behavior should be creating a composer.json similar to the base dist. If you still like to provide to create a composer.json without the minimal scripts part you should consider using an option for this explicity.

**Comment by sypets** [comment]
Thanks for the feedback. I did also think about adding a require for typo3_console in any case. I think that is what I should do. 

Another option I thought about was fetching the composer.json from the base dist.

But I currently would like to keep this extension simple and offer only minimal functionality  which should work even in edge cases.

----

Some points not related to this extension:

1. IMHO if typo3_console is required to run TYPO3 with Composer and Composer is recommended, I think we should also point this out even more clearly than currently in Installation Guide
2. Ideally, typo3_console should be added to core (but I believe this was already discussed)
3. btw. I also thought about the helper script on get.typo3.org: https://get.typo3.org/misc/composer/helper
    If you use just the require commands you will get a composer.json without the scripts. I am afraid, some 
    people will use it like that. Is that something that could also be added to the helper script, that a sample composer.json gets 
    displayed and can be copied? (like in my extension where you have both alternatives: commands or composer.json)

**Comment by gilbertsoft** [comment]
> Thanks for the feedback. I did also think about adding a require for typo3_console in any case. I think that is what I should do.

Yes, that's fine. If needed, I don't know a use case, but users often do strange stuff, you can allow to disable this behavior with an option.

> Another option I thought about was fetching the composer.json from the base dist.

That's also a good idea. Just make sure you fetch the correct version. At the moment there is a bug with the composer scripts, the order is not correct. You did this fix here some days ago. I already discussed this with Helmut and we will fix the base dist later this day.

> Some points not related to this extension:
> 
>     1. IMHO if typo3_console is required to run TYPO3 with Composer and Composer is recommended, I think we should also point this out even more clearly than currently in Installation Guide

TYPO3 Console is definitively required or the PackageStates.php must be updated manually by the user.

>     2. Ideally, typo3_console should be added to core (but I believe this was already discussed)

The problem here is the Core is not ready for it but there will come the time when everything is ready for this step. There were multiple changes in that area in the last major releases but there is still work to do... The main problem here is the bootstrap of the core which is always done fully what is not always possible in a broken system and ends with exceptions. The Console has an own bootstrap here and allows to define various stages, means how much must be available to run a command.

>     3. btw. I also thought about the helper script on get.typo3.org: https://get.typo3.org/misc/composer/helper
>        If you use just the require commands you will get a composer.json without the scripts. I am afraid, some
>        people will use it like that. Is that something that could also be added to the helper script, that a sample composer.json gets
>        displayed and can be copied? (like in my extension where you have both alternatives: commands or composer.json)

I also have plans for get.t3o in that area and I guess Benni also for the Core for v11, we are regularly in contact to discuss new features here. Currently I'm migrating the sitepackage builder to get.t3o and the next step will be a new project builder. After that I will think about other optimizations but your concept looks fine so far. We already discused a solution in March to let the user upload the PackageStates.php and generate a composer.json with that information but your solution with an extension is better imho. I let you know if we decide to integrate something similar to the Core.

BTW not related to this issue, one little optimization which could be done is out sourcing the most of the code from the command to a service and call that service from the command instead. This also makes the code reusable in other extensions e.g.

**Comment by gilbertsoft** [comment]
TYPO3/TYPO3.CMS.BaseDistribution#28
TYPO3/TYPO3.CMS.BaseDistribution#29
